#!/bin/bash

case $1 in
	auto)
		repo init -b $2 -u $3
		repo sync -c -j$4
		source build/envsetup.sh
		lunch $2
		m -j$3
		;;
	
	init)
		git config --global user.name "Automated Access"
		git config --global user.email "iamateapot@example.com"
		repo init -b $2 -u $3
		repo sync -c -j$4
		source build/envsetup.sh
		;;
	
	configure)
		lunch $2
		;;
	
	build)
		if [ -n $2 ]; then m -j$2; else m; fi
		;;
	
	*)
		echo <<EOF
You need to specify an action!
Available actions are: auto, init, configure, build
auto: wrapper auto
init: wrapper init {AOSP_BRANCH) {AOSP_REPO_URL} {SYNC_THREADS}
configure: wrapper configure {LUNCH_TARGET}
build: wrapper build [BUILD_THREADS]
EOF
		;;
esac
